# Generated by Django 5.2.5 on 2026-04-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telegram_bot_token',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telegram_bot_url',
        ),
    ]
