# Generated by Django 5.2.5 on 2026-02-06 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_pass_man', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smartpassword',
            name='smart_pass__login_0ff907_idx',
        ),
        migrations.RemoveField(
            model_name='smartpassword',
            name='login',
        ),
        migrations.AddField(
            model_name='smartpassword',
            name='description',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='smartpassword',
            index=models.Index(fields=['description'], name='smart_pass__descrip_fbde22_idx'),
        ),
    ]
