# Generated by Django 5.2.5 on 2026-04-02 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smart_passwords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smartpassword',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_passwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='smartpassword',
            index=models.Index(fields=['user', 'created_at'], name='smart_passw_user_id_2587db_idx'),
        ),
        migrations.AddIndex(
            model_name='smartpassword',
            index=models.Index(fields=['public_key'], name='smart_passw_public__decae0_idx'),
        ),
        migrations.AddIndex(
            model_name='smartpassword',
            index=models.Index(fields=['description'], name='smart_passw_descrip_20298a_idx'),
        ),
    ]
